//Script generated by LayerScriptGenerator.cs

namespace StorkStudios.CoreNest
{
	public enum Layer
	{
		Default = 0,
		TransparentFX = 1,
		Ignore_Raycast = 2,
		Water = 4,
		UI = 5,
	}
	
	public static class LayerExtensions
	{
		public static int GetLayerIndex(this Layer value)
		{
			return (int)value;
		}
	}
}
