//Script generated by TagScriptGenerator.cs

namespace StorkStudios.CoreNest
{
	public enum Tag
	{
		[StringValue(@"Untagged")]
		Untagged,
		
		[StringValue(@"Respawn")]
		Respawn,
		
		[StringValue(@"Finish")]
		Finish,
		
		[StringValue(@"EditorOnly")]
		EditorOnly,
		
		[StringValue(@"MainCamera")]
		MainCamera,
		
		[StringValue(@"Player")]
		Player,
		
		[StringValue(@"GameController")]
		GameController,
		
	}
	
	public static class TagExtensions
	{
		public static string GetTagString(this Tag value)
		{
			return value.GetStringValue();
		}
	}
}
